### ISSUE TITLE
Log-in Page

### ISSUE THREAD

**Issue by fabiglahn** [fabiglahn/bodyworxhub#2]
## Description

My login page opens after a short Loading Screen. 
The user can only log in - there's no registration, because it's a "members only" app, and you register with the team.

It contains a background image, a logo, an input form for e-mail and password as well as a login button.

##
<img width="299" alt="Bildschirmfoto 2021-11-23 um 16 26 09" src="https://user-images.githubusercontent.com/91462476/143052844-6882c06e-7c89-45ab-8f4a-ece5f4895dfc.png">
 Design

## Tasks

- [ ] Component input form
- [ ] Component login button
- [ ] Component login text
